# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0002_auto_20160921_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='\u6807\u9898')),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
                ('publish_date', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('readcount', models.IntegerField(blank=True, verbose_name='\u9605\u8bfb\u6570')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('meta_description', models.CharField(max_length=64)),
                ('articecount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='upload_file',
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(to='Admin.Tags'),
        ),
    ]
