# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20160921_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='articecount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
