# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='Desired_position',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Skills_list',
        ),
        migrations.AlterField(
            model_name='about',
            name='Introduction',
            field=models.TextField(),
        ),
    ]
