# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datetiem', models.DateTimeField()),
                ('image', models.FileField(upload_to='profile/%Y%m%d')),
            ],
        ),
    ]
