# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='A_Classics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d')),
                ('articecount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
                ('tags', models.CharField(blank=True, max_length=1024, verbose_name='\u6807\u7b7e')),
                ('publish_date', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('readcount', models.IntegerField(blank=True, verbose_name='\u9605\u8bfb\u6570')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.A_Classics')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('commentator', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article')),
            ],
        ),
    ]
